apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: admin-service
          image: admin-service:latest
          ports:
            - containerPort: 8081
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/var/log"
              name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service-service
spec:
  selector:
    app: admin-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
