apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      volumes:
        - name: cassandra-pv-storage
          persistentVolumeClaim:
            claimName: cassandra-pv-claim
      containers:
        - name: cassandra
          image: cassandra:latest
          ports:
            - containerPort: 9042
          volumeMounts:
            - mountPath: "/var/lib/cassandra"
              name: cassandra-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
