apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listings-service
  template:
    metadata:
      labels:
        app: listings-service
    spec:
      containers:
        - name: listings-service
          image: listings-service:latest
          ports:
            - containerPort: 8082
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: listings-service-service
spec:
  selector:
    app: listings-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
