apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages-service
  template:
    metadata:
      labels:
        app: messages-service
    spec:
      containers:
        - name: messages-service
          image: messages-service:latest
          ports:
            - containerPort: 8083
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: messages-service-service
spec:
  selector:
    app: messages-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: messages-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: messages-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50