apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages-service
  template:
    metadata:
      labels:
        app: messages-service
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: messages-service
          image: messages-service:latest
          ports:
            - containerPort: 8083
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/var/log"
              name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: messages-service-service
spec:
  selector:
    app: messages-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
