apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: reviews-service
          image: reviews-service:latest
          ports:
            - containerPort: 8085
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/var/log"
              name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service-service
spec:
  selector:
    app: reviews-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
