apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      volumes:
        - name: log-pv-storage
          persistentVolumeClaim:
            claimName: log-pv-claim
      containers:
        - name: reviews-service
          image: reviews-service:latest
          ports:
            - containerPort: 8085
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/var/log"
              name: log-pv-storage
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service-service
spec:
  selector:
    app: reviews-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reviews-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reviews-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
