apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: users-service
          image: users-service:latest
          ports:
            - containerPort: 8086
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/var/log"
              name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: users-service-service
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
