server:
  port: 8082
spring:
  application:
    name: listings
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379

service:
  queue:
    name: listings_queue
