server:
  port: 8080

spring:
  application:
    name: web-server
  rabbitmq:
    host: rabbit-mq-service
    port: 5672
    username: guest
    password: guest

offers-service:
  queue:
    name: offers_queue

listings-service:
  queue:
    name: listings_queue

messages-service:
  queue:
    name: messages_queue

users-service:
  queue:
    name: users_queue

reviews-service:
  queue:
    name: reviews_queue

jwt:
  secret: UDU6td/lppU8wmSexAWL+cxKP3IKmGxM4E9Cov4I0HE=

logging:
  level:
    org:
      springframework:
        security: DEBUG
