apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbit-mq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_CASSANDRA_CONTACT_POINTS
              value: cassandra-service
            - name: SPRING_CASSANDRA_PORT
              value: "9042"
          image: web-server:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000