server:
  port: 8086

spring:
  application:
    name: traderie_user
  rabbitmq:
    host: rabbit-mq-service
    port: 5672
    username: guest
    password: guest

  datasource:
    password: password
    url: jdbc:postgresql://postgres-service:5432/traderie_postgres
    username: traderie_postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
        id:
          new-generator-mappings: false
          type: uuid-char
    show-sql: true

jwt:
  secret: UDU6td/lppU8wmSexAWL+cxKP3IKmGxM4E9Cov4I0HE=

service:
  queue:
    name: users_queue

logging:
  file:
    name: /var/log/users-service/app.log