server:
  port: 8081

spring:
  application:
    name: messages
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: redis-stack-server
      port: 6379
  cassandra:
    contact-points: cassandra:9042
service:
  queue:
    name: messages_queue

logging:
  file:
    name: logs/app.log
