server:
  port: 8083

spring:
  application:
    name: messages
  rabbitmq:
    host: rabbit-mq-service
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: redis-service
      port: 6379
  cassandra:
    contact-points: cassandra-service
    port: 9042
    keyspace-name: traderie_cassandra

service:
  queue:
    name: messages_queue

logging:
  file:
    name: /var/log/app.log
