server:
  port: 8080

spring:
  application:
    name: offers
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000