server:
  port: 8082

spring:
  application:
    name: offers
  rabbitmq:
    host: rabbit-mq-service
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: redis
      port: 6379

  cassandra:
    contact-points: localhost:9042

service:
  queue:
    name: offers_queue
