server:
  port: 8082

spring:
  application:
    name: offers
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: traderie_cassandra

service:
  queue:
    name: offers_queue
