server:
  port: 8081

spring:
  application:
    name: web-server
  rabbitmq:
    host: rabbit-mq-service
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: redis-service
      port: 6379

offers-service:
  queue:
    name: offers_queue_admin

listings-service:
  queue:
    name: listings_queue_admin

messages-service:
  queue:
    name: messages_queue_admin

users-service:
  queue:
    name: users_queue_admin

reviews-service:
  queue:
    name: reviews_queue_admin

admin-service:
  classpath: admin-service/src/main/java/com/massivelyflammableapps/admin/
