server:
  port: 8081

spring:
  application:
    name: web-server
  rabbitmq:
    host: rabbit-mq-service
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: redis-service
      port: 6379

offers-service:
  queue:
    name: offers_queue

listings-service:
  queue:
    name: listings_queue

messages-service:
  queue:
    name: messages_queue

users-service:
  queue:
    name: users_queue

admin-service:
  classpath: admin-service/src/main/java/com/massivelyflammableapps/admin/

logging:
  file:
    name: /var/log/admin-service/app.log
