services:
  spring-boot-app:
    image: messages-service
    ports:
      - "8081:8081"
    depends_on:
      - cassandra
      - rabbitmq
      - redis-stack-server
    volumes:
      - ./logs:/var/log
    restart: always
  
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
  
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  
  redis-stack-server:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    restart: always

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./docker:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - ./logs:/var/log
      - ./docker:/etc/promtail 
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge

 