server:
    port: 8081

spring:
    application:
        name: review_service

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    cassandra:
        schema-action: CREATE_IF_NOT_EXISTS
        request:
            timeout: 10s
        connection:
            connect-timeout: 10s
            init-query-timeout: 10s
        port: 9042
        contact-points: mycassandra
        keyspace-name: traderie_cassandra
    data: 
        redis:
            host: localhost
            port: 6379

service:
    queue:
        name: reviews_queue
