server:
    port: 8081

spring:
    application:
        name: review_service
    cassandra:
        schema-action: CREATE_IF_NOT_EXISTS
        request:
            timeout: 10s
        connection:
            connect-timeout: 10s
            init-query-timeout: 10s
        port: 9042
        contact-points: mycassandra
        keyspace-name: traderie_cassandra
